### ISSUE TITLE
Update library and namespace

### ISSUE THREAD

**Issue by tacman** [jonasarts/phpqrcode-bundle#4]
The namespace for this bundle doesn't follow the conventional naming.  It makes it a bit confusing.

Also, the chillans qr code library is newer, and can be installed with composer.  It looks like this bundle copies the older code into the /lib, 

Alas, I'm just stabbing here, I'm not able to integrate the bundle for a few reasons (e.g. you can't get getParameter() in a bundle), I was hoping this can be updated.

**Comment by jonasarts** [comment]
I will have a look at packagist.org, if it is possible to replace the lib with a dependency now.
The Versioning follows the Symfony releases. V5 is for Symfony 5 and V6 is for Symfony 6. There shouldn't be any getParameter() left in the more up2date code?

Can you give me a quick input about "todays" namespacing convention. I was following the Symfony 3 Standard then.

**Comment by jonasarts** [comment]
The 6.* branch already uses the "chillerlan/php-qrcode" package instead of the /lib. You can switch to 6.* or backport the update to the 5.* branch?
I will update master also to Symfony 6, as it gets it's LTS version.
